plugins {
    id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}

base {
    archivesName = "svc-addon-fabric"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(project.java_version as int)
    withSourcesJar()
}

loom {
    mods {
        svc_addon {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation project(':common')
    implementation "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    runtimeOnly "maven.modrinth:simple-voice-chat:fabric-${project.voicechat_version}"
    runtimeOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}:fabric-stub"
}

processResources {
    inputs.properties(
            version: project.version,
            minecraft_version: project.minecraft_version,
            fabric_loader_version: project.fabric_loader_version,
            fabric_api_version: project.fabric_api_version,
            voicechat_api_version: project.voicechat_api_version
    )
    filesMatching('fabric.mod.json') {
        expand(inputs.properties)
    }
    from(project(':common').sourceSets.main.resources)
}

tasks.named('jar', Jar) {
    from(project(':common').sourceSets.main.output) {
        exclude 'svc_addon-default.properties'
    }
    archiveVersion = "${project.version}+mc${project.minecraft_version}"
}

tasks.named('sourcesJar', Jar) {
    from(project(':common').sourceSets.main.allSource)
    archiveVersion = "${project.version}+mc${project.minecraft_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = project.java_version as int
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Werror']
}
