license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''
Continuous loudness-based proximity range and acoustic path tracing for Simple Voice Chat.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="voicechat"
type="required"
versionRange="[2.6.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="voicechat_api"
type="required"
versionRange="[${voicechat_api_version},)"
ordering="AFTER"
side="BOTH"
